/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  slug: Slug;
  title: InternationalizedArrayString;
  excerpt?: InternationalizedArrayText;
  body: InternationalizedArrayPortableText;
  status: "draft" | "published" | "archived";
  publishedAt?: string;
  cover?: ImageWithMetadata;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  socialImage?: ImageWithMetadata;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithMetadata = {
  _type: "imageWithMetadata";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorative?: boolean;
  alt?: InternationalizedArrayString;
  credit?: string;
  caption?: InternationalizedArrayText;
};

export type InternationalizedArrayPortableText = Array<
  {
    _key: string;
  } & InternationalizedArrayPortableTextValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  name: string;
  slug: Slug;
  status: "partner" | "pilot" | "interested";
  coordinates?: Geopoint;
  website?: string;
  logo?: ImageWithMetadata;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  slug: Slug;
  title: InternationalizedArrayString;
  description?: InternationalizedArrayPortableText;
  startsAt: string;
  endsAt?: string;
  location?: string;
  registrationUrl?: string;
  status: "scheduled" | "cancelled";
  image?: ImageWithMetadata;
};

export type FaqCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqCategory";
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  question: InternationalizedArrayString;
  answer: InternationalizedArrayPortableText;
  category: FaqCategoryReference;
  order: number;
};

export type FaqCategory = {
  _id: string;
  _type: "faqCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey: string;
  label: InternationalizedArrayString;
  order: number;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  name: string;
  role: InternationalizedArrayString;
  portrait: ImageWithMetadata;
  stageImage?: ImageWithMetadata;
  quote?: InternationalizedArrayText;
};

export type LocaleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locale";
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tag: "de" | "en";
  isDefault?: boolean;
  fallback?: LocaleReference;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  imprint: LegalPage;
  privacy: LegalPage;
};

export type LegalPage = {
  _type: "legalPage";
  status: "placeholder" | "review" | "approved";
  intro: PageIntro;
  body?: InternationalizedArrayPortableText;
  seo?: Seo;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  navigationLabel: InternationalizedArrayString;
  statsTemplate: InternationalizedArrayString;
  search: FaqSearchCopy;
  seo?: Seo;
};

export type FaqSearchCopy = {
  _type: "faqSearchCopy";
  label: InternationalizedArrayString;
  placeholder: InternationalizedArrayString;
  clearLabel: InternationalizedArrayString;
  resultsTemplate: InternationalizedArrayString;
  noResultsTitle: InternationalizedArrayString;
  noResultsTemplate: InternationalizedArrayText;
  resetLabel: InternationalizedArrayString;
};

export type PageIntro = {
  _type: "pageIntro";
  kicker: InternationalizedArrayString;
  title: InternationalizedArrayString;
  lead: InternationalizedArrayText;
};

export type MaterialsPage = {
  _id: string;
  _type: "materialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  resources: ResourceSection;
  links: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  seo?: Seo;
};

export type ResourceSection = {
  _type: "resourceSection";
  heading: SectionHeading;
  items: Array<
    {
      _key: string;
    } & ResourcePlacement
  >;
};

export type ContributePage = {
  _id: string;
  _type: "contributePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  benefits: FeatureSection;
  steps: Array<
    {
      _key: string;
    } & NumberedStep
  >;
  quote: QuoteItem;
  implementation: ImplementationSection;
  partnerMap: PartnerMapCopy;
  seo?: Seo;
};

export type PartnerMapCopy = {
  _type: "partnerMapCopy";
  heading: InternationalizedArrayString;
  lead: InternationalizedArrayText;
  networkNote: InternationalizedArrayString;
  networkActionLabel: InternationalizedArrayString;
  mapImageAlt: InternationalizedArrayString;
  statusLabel: InternationalizedArrayString;
  partnerStatus: InternationalizedArrayString;
  pilotStatus: InternationalizedArrayString;
  interestedStatus: InternationalizedArrayString;
  websiteLabel: InternationalizedArrayString;
  noLocation: InternationalizedArrayString;
  empty: InternationalizedArrayText;
  selectionHint: InternationalizedArrayString;
  locationSingular: InternationalizedArrayString;
  locationPlural: InternationalizedArrayString;
  legendLabel: InternationalizedArrayString;
};

export type ImplementationSection = {
  _type: "implementationSection";
  heading: SectionHeading;
  body: InternationalizedArrayText;
  items: Array<
    {
      _key: string;
    } & LocalizedListItem
  >;
};

export type QuoteItem = {
  _type: "quoteItem";
  body: InternationalizedArrayText;
  source: InternationalizedArrayString;
  role?: InternationalizedArrayString;
};

export type FeatureSection = {
  _type: "featureSection";
  heading: SectionHeading;
  items: Array<
    {
      _key: string;
    } & FeatureItem
  >;
};

export type UseCasesPage = {
  _id: string;
  _type: "useCasesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  useCases: Array<
    {
      _key: string;
    } & FeatureItem
  >;
  seo?: Seo;
};

export type JoinPage = {
  _id: string;
  _type: "joinPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  sections: Array<
    {
      _key: string;
    } & TextSection
  >;
  networkMap: MapEmbedCopy;
  links: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  seo?: Seo;
};

export type MapEmbedCopy = {
  _type: "mapEmbedCopy";
  heading: SectionHeading;
  caption: InternationalizedArrayText;
  accessibleTitle: InternationalizedArrayString;
};

export type SemanticStandardsPage = {
  _id: string;
  _type: "semanticStandardsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  sections: Array<
    {
      _key: string;
    } & TextSection
  >;
  links: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  seo?: Seo;
};

export type TechnicalStandardsPage = {
  _id: string;
  _type: "technicalStandardsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  sections: Array<
    {
      _key: string;
    } & TextSection
  >;
  dataFlow: DataFlowSection;
  video: VideoSection;
  comic: ComicReferenceSection;
  resources: ResourceSection;
  links: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  seo?: Seo;
};

export type ComicStripReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "comicStrip";
};

export type ComicReferenceSection = {
  _type: "comicReferenceSection";
  heading: SectionHeading;
  comic: ComicStripReference;
};

export type VideoSection = {
  _type: "videoSection";
  heading: SectionHeading;
  caption: InternationalizedArrayText;
  youtubeId: string;
  accessibleTitle: InternationalizedArrayString;
};

export type DataFlowSection = {
  _type: "dataFlowSection";
  heading: SectionHeading;
  stages: Array<
    {
      _key: string;
    } & DataFlowStage
  >;
  caption: InternationalizedArrayText;
};

export type TeamPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamPage";
};

export type ConceptPage = {
  _id: string;
  _type: "conceptPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  sections: Array<
    {
      _key: string;
    } & TextSection
  >;
  links: Array<
    {
      _key: string;
    } & InternalOrExternalLink
  >;
  timeline: TimelineSection;
  teamPage: TeamPageReference;
  seo?: Seo;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type TeamPage = {
  _id: string;
  _type: "teamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  people: Array<
    {
      _key: string;
    } & PersonReference
  >;
  portraitFallback: InternationalizedArrayString;
  stageAltTemplate: InternationalizedArrayString;
  seo?: Seo;
};

export type TimelineSection = {
  _type: "timelineSection";
  heading: SectionHeading;
  locationLabel: InternationalizedArrayString;
  sourceLabel: InternationalizedArrayString;
  journey: JourneySection;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: HomeHero;
  benefits: FeatureSection;
  video: VideoSection;
  network: NetworkSection;
  comic: ComicReferenceSection;
  stakeholders: FeatureSection;
  quotes: QuoteSection;
  pitch: TextSection;
  trust: BrandLockup;
  seo?: Seo;
};

export type BrandLockup = {
  _type: "brandLockup";
  label: InternationalizedArrayString;
  logo: ImageWithMetadata;
};

export type TextSection = {
  _type: "textSection";
  eyebrow: InternationalizedArrayString;
  heading: InternationalizedArrayString;
  body: InternationalizedArrayPortableText;
  image?: ImageWithMetadata;
};

export type QuoteSection = {
  _type: "quoteSection";
  heading: SectionHeading;
  items: Array<
    {
      _key: string;
    } & QuoteItem
  >;
};

export type NetworkSection = {
  _type: "networkSection";
  heading: SectionHeading;
  total: number;
  totalLabel: InternationalizedArrayString;
  mapTitle: InternationalizedArrayString;
  mapCaption: InternationalizedArrayString;
  segments: Array<
    {
      _key: string;
    } & NetworkSegment
  >;
};

export type HomeHero = {
  _type: "homeHero";
  technologyLabel: InternationalizedArrayString;
  title: InternationalizedArrayString;
  summary: InternationalizedArrayText;
  primaryAction: InternalOrExternalLink;
  secondaryAction: InternalOrExternalLink;
  image: ImageWithMetadata;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: InternationalizedArrayString;
  siteDescription: InternationalizedArrayText;
  navigation: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  menuLabel: InternationalizedArrayString;
  menuDescription: InternationalizedArrayString;
  languageSwitcher: LanguageSwitcherCopy;
  footer: FooterCopy;
  comingSoon: ComingSoonCopy;
  postUi: PostUiCopy;
  eventUi: EventUiCopy;
  defaultSeo?: Seo;
};

export type EventUiCopy = {
  _type: "eventUiCopy";
  intro: PageIntro;
  upcomingHeading: InternationalizedArrayString;
  pastHeading: InternationalizedArrayString;
  registerLabel: InternationalizedArrayString;
  noUpcoming: InternationalizedArrayText;
  empty: EmptyStateCopy;
};

export type PostUiCopy = {
  _type: "postUiCopy";
  intro: PageIntro;
  readMoreLabel: InternationalizedArrayString;
  publishedAtLabel: InternationalizedArrayString;
  backToListLabel: InternationalizedArrayString;
  empty: EmptyStateCopy;
};

export type ComingSoonCopy = {
  _type: "comingSoonCopy";
  kicker: InternationalizedArrayString;
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
  backToHomeLabel: InternationalizedArrayString;
};

export type FooterCopy = {
  _type: "footerCopy";
  imprintLabel: InternationalizedArrayString;
  privacyLabel: InternationalizedArrayString;
  supportedByLabel: InternationalizedArrayString;
  sitemapLabel: InternationalizedArrayString;
  rightsStatement: InternationalizedArrayString;
  copyrightTemplate: InternationalizedArrayString;
  logos: Array<
    {
      _key: string;
    } & FooterLogo
  >;
};

export type LanguageSwitcherCopy = {
  _type: "languageSwitcherCopy";
  labelTemplate: InternationalizedArrayString;
  germanLabel: InternationalizedArrayString;
  englishLabel: InternationalizedArrayString;
};

export type EmptyStateCopy = {
  _type: "emptyStateCopy";
  kicker: InternationalizedArrayString;
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
};

export type FooterLogo = {
  _type: "footerLogo";
  sourceKey: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: InternationalizedArrayString;
  website?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type NavigationItem = {
  _type: "navigationItem";
  sourceKey: string;
  label: InternationalizedArrayString;
  route: "/konzeption" | "/jetzt-mitmachen" | "/materialien" | "/faq" | "/team";
  placements: Array<"header" | "footer">;
};

export type SectionHeading = {
  _type: "sectionHeading";
  eyebrow: InternationalizedArrayString;
  heading: InternationalizedArrayString;
  lead?: InternationalizedArrayText;
};

export type ResourceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "resource";
};

export type ResourcePlacement = {
  _type: "resourcePlacement";
  resource: ResourceReference;
  titleOverride?: InternationalizedArrayString;
  bodyOverride?: InternationalizedArrayText;
  labelOverride?: InternationalizedArrayString;
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey: string;
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
  link: InternalOrExternalLink;
};

export type InternalOrExternalLink = {
  _type: "internalOrExternalLink";
  label: InternationalizedArrayString;
  kind: "internal" | "external";
  internalTarget?: string;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type DataFlowStage = {
  _type: "dataFlowStage";
  sourceKey: string;
  heading: InternationalizedArrayString;
  subheading: InternationalizedArrayString;
  items: Array<
    {
      _key: string;
    } & DataFlowItem
  >;
};

export type DataFlowItem = {
  _type: "dataFlowItem";
  label: InternationalizedArrayString;
  format?: InternationalizedArrayString;
  channelKind: "standard" | "orif";
};

export type JourneySection = {
  _type: "journeySection";
  heading: InternationalizedArrayString;
  lead: InternationalizedArrayText;
  selectionHint: InternationalizedArrayString;
  previousLabel: InternationalizedArrayString;
  nextLabel: InternationalizedArrayString;
  progressLabel: InternationalizedArrayString;
  stations: Array<
    {
      _key: string;
    } & JourneyStation
  >;
};

export type JourneyStation = {
  _type: "journeyStation";
  sourceKey: string;
  tag: InternationalizedArrayString;
  phase: InternationalizedArrayString;
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
  chips: Array<
    {
      _key: string;
    } & LocalizedListItem
  >;
};

export type NetworkSegment = {
  _type: "networkSegment";
  value: number;
  label: InternationalizedArrayString;
};

export type ComicStrip = {
  _id: string;
  _type: "comicStrip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey: string;
  internalName: string;
  frames: Array<
    {
      _key: string;
    } & ComicFrame
  >;
};

export type ComicFrame = {
  _type: "comicFrame";
  sourceKey: string;
  image: ImageWithMetadata;
  title: InternationalizedArrayString;
  caption: InternationalizedArrayText;
};

export type NumberedStep = {
  _type: "numberedStep";
  sourceKey: string;
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
};

export type LocalizedListItem = {
  _type: "localizedListItem";
  text: InternationalizedArrayString;
};

export type FeatureItem = {
  _type: "featureItem";
  sourceKey: string;
  icon?:
    | "sparkles"
    | "megaphone"
    | "users"
    | "building"
    | "archive"
    | "code"
    | "briefcase";
  title: InternationalizedArrayString;
  body: InternationalizedArrayText;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type InternationalizedArrayPortableTextValue = {
  _type: "internationalizedArrayPortableTextValue";
  value?: PortableText;
  language: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Post
  | Seo
  | SanityImageAssetReference
  | ImageWithMetadata
  | InternationalizedArrayPortableText
  | InternationalizedArrayText
  | InternationalizedArrayString
  | Slug
  | Partner
  | Geopoint
  | Event
  | FaqCategoryReference
  | FaqItem
  | FaqCategory
  | Person
  | LocaleReference
  | Locale
  | Legal
  | LegalPage
  | FaqPage
  | FaqSearchCopy
  | PageIntro
  | MaterialsPage
  | ResourceSection
  | ContributePage
  | PartnerMapCopy
  | ImplementationSection
  | QuoteItem
  | FeatureSection
  | UseCasesPage
  | JoinPage
  | MapEmbedCopy
  | SemanticStandardsPage
  | TechnicalStandardsPage
  | ComicStripReference
  | ComicReferenceSection
  | VideoSection
  | DataFlowSection
  | TeamPageReference
  | ConceptPage
  | PersonReference
  | TeamPage
  | TimelineSection
  | HomePage
  | BrandLockup
  | TextSection
  | QuoteSection
  | NetworkSection
  | HomeHero
  | SiteSettings
  | EventUiCopy
  | PostUiCopy
  | ComingSoonCopy
  | FooterCopy
  | LanguageSwitcherCopy
  | EmptyStateCopy
  | FooterLogo
  | SanityImageCrop
  | SanityImageHotspot
  | NavigationItem
  | SectionHeading
  | ResourceReference
  | ResourcePlacement
  | Resource
  | InternalOrExternalLink
  | DataFlowStage
  | DataFlowItem
  | JourneySection
  | JourneyStation
  | NetworkSegment
  | ComicStrip
  | ComicFrame
  | NumberedStep
  | LocalizedListItem
  | FeatureItem
  | PortableText
  | InternationalizedArrayPortableTextValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
