/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  slug: Slug;
  title?: InternationalizedArrayString;
  excerpt?: InternationalizedArrayText;
  body?: InternationalizedArrayPortableText;
  publishedAt: string;
  cover?: ImageWithMetadata;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  socialImage?: ImageWithMetadata;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithMetadata = {
  _type: "imageWithMetadata";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorative?: boolean;
  alt?: InternationalizedArrayString;
  credit?: string;
  caption?: InternationalizedArrayText;
};

export type InternationalizedArrayPortableText = Array<
  {
    _key: string;
  } & InternationalizedArrayPortableTextValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  name: string;
  slug: Slug;
  status: "partner" | "pilot" | "interested";
  coordinates: Geopoint;
  website?: string;
  logo?: ImageWithMetadata;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  slug: Slug;
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayPortableText;
  startsAt: string;
  endsAt?: string;
  location?: string;
  registrationUrl?: string;
  status: "upcoming" | "past" | "cancelled";
  image?: ImageWithMetadata;
};

export type FaqCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqCategory";
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  legacyId?: string;
  question?: InternationalizedArrayString;
  answer?: InternationalizedArrayPortableText;
  category: FaqCategoryReference;
  order: number;
};

export type FaqCategory = {
  _id: string;
  _type: "faqCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey: string;
  label?: InternationalizedArrayString;
  order: number;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceKey?: string;
  name: string;
  role?: InternationalizedArrayString;
  portrait: ImageWithMetadata;
  stageImage?: ImageWithMetadata;
  quote?: InternationalizedArrayText;
};

export type LocaleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locale";
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tag: "de" | "en";
  isDefault?: boolean;
  fallback?: LocaleReference;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  todo?: boolean;
  imprint?: InternationalizedArrayPortableText;
  privacy?: InternationalizedArrayPortableText;
};

export type TeamPage = {
  _id: string;
  _type: "teamPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type PageIntro = {
  _type: "pageIntro";
  kicker?: InternationalizedArrayString;
  title?: InternationalizedArrayString;
  lead?: InternationalizedArrayText;
};

export type MaterialsPage = {
  _id: string;
  _type: "materialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type ContributePage = {
  _id: string;
  _type: "contributePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type UseCasesPage = {
  _id: string;
  _type: "useCasesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type JoinPage = {
  _id: string;
  _type: "joinPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type SemanticStandardsPage = {
  _id: string;
  _type: "semanticStandardsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type TechnicalStandardsPage = {
  _id: string;
  _type: "technicalStandardsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type ConceptPage = {
  _id: string;
  _type: "conceptPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: PageIntro;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: InternationalizedArrayString;
  siteDescription?: InternationalizedArrayText;
  navigation?: Array<{
    key: Slug;
    label?: InternationalizedArrayString;
    href: string;
    _type: "navigationItem";
    _key: string;
  }>;
  footerCopyright?: InternationalizedArrayString;
  defaultSeo?: Seo;
};

export type InternalOrExternalLink = {
  _type: "internalOrExternalLink";
  label?: InternationalizedArrayString;
  kind: "internal" | "external";
  href: string;
  openInNewTab?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type InternationalizedArrayPortableTextValue = {
  _type: "internationalizedArrayPortableTextValue";
  value?: PortableText;
  language: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Post
  | Seo
  | SanityImageAssetReference
  | ImageWithMetadata
  | InternationalizedArrayPortableText
  | InternationalizedArrayText
  | InternationalizedArrayString
  | Slug
  | Partner
  | Geopoint
  | Event
  | FaqCategoryReference
  | FaqItem
  | FaqCategory
  | Person
  | LocaleReference
  | Locale
  | Legal
  | TeamPage
  | PageIntro
  | MaterialsPage
  | ContributePage
  | UseCasesPage
  | JoinPage
  | SemanticStandardsPage
  | TechnicalStandardsPage
  | ConceptPage
  | HomePage
  | SiteSettings
  | InternalOrExternalLink
  | SanityImageCrop
  | SanityImageHotspot
  | PortableText
  | InternationalizedArrayPortableTextValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
